export enum EmailTrigger {
  ORDER_PLACED = 'ORDER_PLACED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_PROCESSED = 'ORDER_PROCESSED',
  ORDER_CLOSED = 'ORDER_CLOSED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  WELCOME_EMAIL = 'WELCOME_EMAIL',
}