/**
 * Type definition for WordPress/WooCommerce order metadata.
 *
 * Represents a mapping of order meta keys to their corresponding values,
 * where each key from WPOrderMetaKeys can have a value of various types
 * including primitives, arrays, objects, or null.
 *
 * @template WPOrderMetaKeys - The allowed meta key names for order metadata
 */
export type WPOrderMeta = {
    [key in WPOrderMetaKeys]: string | number | boolean | [] | object | null;
};

export enum WPOrderMetaKeys {
    _wp_trash_meta_status = '_wp_trash_meta_status',
    _billing_address_index = '_billing_address_index',
    _wp_trash_meta_time = '_wp_trash_meta_time',
    locked_netto_total = 'locked_netto_total',
    _wc_order_attribution_referrer = '_wc_order_attribution_referrer',
    _wc_order_attribution_session_entry = '_wc_order_attribution_session_entry',
    _wc_order_attribution_session_start_time = '_wc_order_attribution_session_start_time',
    approved = 'approved',
    _orig_total = '_orig_total',
    locked_brutto_total = 'locked_brutto_total',
    locked_tax_total = 'locked_tax_total',
    futar = 'futar',
    _deleted_from = '_deleted_from',
    billing_innvoice_email = 'billing_innvoice_email',
    _wc_google_analytics_pro_session_params = '_wc_google_analytics_pro_session_params',
    _wc_google_analytics_pro_identity = '_wc_google_analytics_pro_identity',
    _wc_billingo_plus_draft_id = '_wc_billingo_plus_draft_id',
    _wc_billingo_plus_draft_name = '_wc_billingo_plus_draft_name',
    _wc_billingo_plus_draft_pdf = '_wc_billingo_plus_draft_pdf',
    _wc_billingo_plus_draft_url = '_wc_billingo_plus_draft_url',
    summary_id = 'summary_id',
    _wc_order_attribution_user_agent = '_wc_order_attribution_user_agent',
    _shipping_address_index = '_shipping_address_index',
    innvoice_payment_due = 'innvoice_payment_due',
    _innvoice_payment_due = '_innvoice_payment_due',
    order_iscompany_override = 'order_iscompany_override',
    _wc_order_attribution_session_pages = '_wc_order_attribution_session_pages',
    shipcost_override = 'shipcost_override',
    _shipping_ring_no = '_shipping_ring_no',
    billing_tax_number = 'billing_tax_number',
    change_log = 'change_log',
    innvoice_block_create = 'innvoice_block_create',
    _billing_ring_no = '_billing_ring_no',
    _wc_google_analytics_pro_placed = '_wc_google_analytics_pro_placed',
    mailchimp_woocommerce_is_subscribed = 'mailchimp_woocommerce_is_subscribed',
    _wc_google_analytics_pro_tracked = '_wc_google_analytics_pro_tracked',
    _wc_google_analytics_pro_tracked_in_ua = '_wc_google_analytics_pro_tracked_in_ua',
    _innvoice_block_create = '_innvoice_block_create',
    _innvoice_szamlazhato = '_innvoice_szamlazhato',
    shipping_email = 'shipping_email',
    _innvoice_szamla_sorszam = '_innvoice_szamla_sorszam',
    _innvoice_szamla_url = '_innvoice_szamla_url',
    _shipping_time = '_shipping_time',
    admin_note = 'admin_note',
    _shipping_date = '_shipping_date',
    old_order_id = 'old_order_id',
    _billing_innvoice_email = '_billing_innvoice_email',
    _billing_tax_number = '_billing_tax_number',
    mailchimp_woocommerce_landing_site = 'mailchimp_woocommerce_landing_site',
    _alg_wc_cog_order_items_cost = '_alg_wc_cog_order_items_cost',
    _alg_wc_cog_order_profit = '_alg_wc_cog_order_profit',
    _alg_wc_cog_order_profit_percent = '_alg_wc_cog_order_profit_percent',
    trp_language = 'trp_language',
    _wc_order_attribution_utm_medium = '_wc_order_attribution_utm_medium',
    _fees_hash = '_fees_hash',
    simple_id = 'simple_id',
    simple_status = 'simple_status',
    _metorik_referer = '_metorik_referer',
    _wc_order_attribution_utm_content = '_wc_order_attribution_utm_content',
    _metorik_session_start_time = '_metorik_session_start_time',
    _metorik_source_type = '_metorik_source_type',
    _metorik_utm_content = '_metorik_utm_content',
    _metorik_utm_medium = '_metorik_utm_medium',
    _alg_wc_cog_order_price = '_alg_wc_cog_order_price',
    _wc_order_attribution_session_count = '_wc_order_attribution_session_count',
    _metorik_session_count = '_metorik_session_count',
    _wc_order_attribution_utm_creative_format = '_wc_order_attribution_utm_creative_format',
    _metorik_session_pages = '_metorik_session_pages',
    _wc_order_attribution_utm_marketing_tactic = '_wc_order_attribution_utm_marketing_tactic',
    _wc_order_attribution_utm_source_platform = '_wc_order_attribution_utm_source_platform',
    _metorik_utm_source = '_metorik_utm_source',
    _taxes_hash = '_taxes_hash',
    _metorik_session_entry = '_metorik_session_entry',
    _wc_other_metorik_opt_in = '_wc_other/metorik/opt-in',
    two_step = 'two_step',
    _shipping_hash = '_shipping_hash',
    _alg_wc_cog_order_cost = '_alg_wc_cog_order_cost',
    _alg_wc_cog_order_profit_margin = '_alg_wc_cog_order_profit_margin',
    is_vat_exempt = 'is_vat_exempt',
    _coupons_hash = '_coupons_hash',
    _wc_order_attribution_device_type = '_wc_order_attribution_device_type',
    _wc_order_attribution_utm_source = '_wc_order_attribution_utm_source',
    _edit_lock = '_edit_lock',
    _wc_order_attribution_source_type = '_wc_order_attribution_source_type',

    //PostMeta
    _billing_address_1 = '_billing_address_1',
    _billing_city = '_billing_city',
    _billing_country = '_billing_country',
    _billing_email = '_billing_email',
    _billing_first_name = '_billing_first_name',
    _billing_phone = '_billing_phone',
    _billing_postcode = '_billing_postcode',
    _shipping_address_1 = '_shipping_address_1',
    _shipping_city = '_shipping_city',
    _shipping_country = '_shipping_country',
    _shipping_first_name = '_shipping_first_name',
    _shipping_postcode = '_shipping_postcode',
    _billing_additional_emails = '_billing_additional_emails',
}
